### ISSUE TITLE
Add Categories to Posts

### ISSUE THREAD

**Issue by adamhepton** [FirsRdJnr/skybet.github.io#17]

**Comment by adamhepton** [comment]
https://github.com/FirsRdJnr/skybet.github.io/commit/6e58a4db793e1665348cae71507edee8e10b8061

Content and basic styling added, but I know @FirsRdJnr will want to review the style of how the category is added to posts.

**Comment by FirsRdJnr** [comment]
fixed with 56daaa3057cdec751fac678781f1c7db08b93563
