### ISSUE TITLE
Consistent use of “Sky Betting & Gaming”

### ISSUE THREAD

**Issue by cmbuckley** [FirsRdJnr/skybet.github.io#19]
Brand guidelines say we should use an ampersand in the name: http://media.skybet.com/brandhub/downloads/Sky-Betting-and-Gaming-Brand-Guide-2015.pdf

There are a few mentions of “Sky Betting and Gaming” through the codebase.

**Comment by adamhepton** [comment]
Fixed within skybet/skybet.github.io#18, a few additions to be done within this branch that will find their way upstream with style.
